name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install flake8 bandit
          flake8 .
          bandit -r .

  tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          pip install -r requirements.txt || true
          pip install pytest
          pytest tests/ -v || true

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-redis-tp:${{ github.sha }} .
      - name: Smoke-run container
        run: |
          docker run -d -p 8000:8000 --name test_container ${{ secrets.DOCKER_USERNAME }}/fastapi-redis-tp:${{ github.sha }}
          sleep 5
          docker ps
      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-redis-tp:${{ github.sha }}
